/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/items/Gate_valla_2.glb -o src/components/Door.jsx -r public -k 
*/

import React, { useState } from 'react'
import { useGLTF, useCursor } from '@react-three/drei'
import { socket } from './SocketManager'




export function Door(props) {
  //const [open, setOpen] = useState(props.open)
  const [onObject, setOnObject] = useState(false);
  const rotationA = props.open ? [2.20, 1.65, 4] : [0, 0, 0]
  const rotationB = props.open ? [-2.20, -1.45, 4] : [0, 0, 0]
  //Why it is rendering multiple times?
  //console.log(rotationB)
  const handleDoor = () => {


  }
  useCursor(onObject);
  const { nodes, materials } = useGLTF('/models/items/Gate_Valla_2.glb')
  return (
    <group {...props} dispose={null}
      onClick={() => {
        socket.emit(
          "actionDoor",
          props.objectID,
          !props.open
        )
        //setOpen(!open)

      }}
      onPointerEnter={() => setOnObject(true)}
      onPointerLeave={() => setOnObject(false)}
    >
      <mesh name="fence_gate" geometry={nodes.fence_gate.geometry} material={materials['HalloweenBits.040']}>
        <mesh rotation={rotationA} name="fence_gate_left" geometry={nodes.fence_gate_left.geometry} material={materials['HalloweenBits.040']} position={[0.75, 0, 0]} />
        <mesh rotation={rotationB} name="fence_gate_right" geometry={nodes.fence_gate_right.geometry} material={materials['HalloweenBits.040']} position={[-0.75, 0, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/items/Gate_Valla_2.glb')
